version: '3.8'

services:
  server: #nginx  
    # image: 'nginx:stable-alpine' #image 는 따옴표로 설정하는것이 안전. 
    # build : 설정되어있는 경로에 있는 dockerfile를 이용하여 이미지를 빌드한다. 
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80' # document 설정
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # document 설정
    depends_on:
      - php
      - mysql
  php: # port 9000은 여기가 아니라 nginx.conf 에서.
    build:
      context: . # context와 dockerfile은 짝궁
      dockerfile: dockerfiles/php.dockerfile  
    volumes:
      - ./src:/var/www/html:delegated # dele  gated : 안전성은 떨어지지만 속도가 향상됨.
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ['npm']
    volumes:
      - ./src:/var/www/html
